// <auto-generated />
using System;
using Intex2026.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intex2026.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Intex2026.Api.Models.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("donation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonationId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CampaignName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("campaign_name");

                    b.Property<string>("ChannelSource")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("channel_source");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency_code");

                    b.Property<DateTime?>("DonationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("donation_date");

                    b.Property<string>("DonationType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("donation_type");

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("estimated_value");

                    b.Property<string>("ImpactUnit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("impact_unit");

                    b.Property<bool?>("IsRecurring")
                        .HasColumnType("bit")
                        .HasColumnName("is_recurring");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int?>("ReferralPostId")
                        .HasColumnType("int")
                        .HasColumnName("referral_post_id");

                    b.Property<int>("SupporterId")
                        .HasColumnType("int")
                        .HasColumnName("supporter_id");

                    b.HasKey("DonationId");

                    b.ToTable("donations", (string)null);
                });

            modelBuilder.Entity("Intex2026.Api.Models.HomeVisitation", b =>
                {
                    b.Property<int>("VisitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("visitation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitationId"));

                    b.Property<string>("FamilyCooperationLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("family_cooperation_level");

                    b.Property<string>("FamilyMembersPresent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("family_members_present");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool?>("FollowUpNeeded")
                        .HasColumnType("bit")
                        .HasColumnName("follow_up_needed");

                    b.Property<string>("FollowUpNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("follow_up_notes");

                    b.Property<string>("LocationVisited")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_visited");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observations");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("purpose");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<bool?>("SafetyConcernsNoted")
                        .HasColumnType("bit")
                        .HasColumnName("safety_concerns_noted");

                    b.Property<string>("SocialWorker")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("social_worker");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("visit_date");

                    b.Property<string>("VisitOutcome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("visit_outcome");

                    b.Property<string>("VisitType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("visit_type");

                    b.HasKey("VisitationId");

                    b.ToTable("home_visitations", (string)null);
                });

            modelBuilder.Entity("Intex2026.Api.Models.ProcessRecording", b =>
                {
                    b.Property<int>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("recording_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordingId"));

                    b.Property<bool?>("ConcernsFlagged")
                        .HasColumnType("bit")
                        .HasColumnName("concerns_flagged");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("EmotionalStateEnd")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emotional_state_end");

                    b.Property<string>("EmotionalStateObserved")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emotional_state_observed");

                    b.Property<string>("FollowUpActions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("follow_up_actions");

                    b.Property<string>("InterventionsApplied")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("interventions_applied");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes_restricted");

                    b.Property<bool?>("ProgressNoted")
                        .HasColumnType("bit")
                        .HasColumnName("progress_noted");

                    b.Property<bool?>("ReferralMade")
                        .HasColumnType("bit")
                        .HasColumnName("referral_made");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<DateTime?>("SessionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("session_date");

                    b.Property<int?>("SessionDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("session_duration_minutes");

                    b.Property<string>("SessionNarrative")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("session_narrative");

                    b.Property<string>("SessionType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("session_type");

                    b.Property<string>("SocialWorker")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("social_worker");

                    b.HasKey("RecordingId");

                    b.ToTable("process_recordings", (string)null);
                });

            modelBuilder.Entity("Intex2026.Api.Models.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidentId"));

                    b.Property<string>("AgeUponAdmission")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("age_upon_admission");

                    b.Property<string>("AssignedSocialWorker")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assigned_social_worker");

                    b.Property<string>("BirthStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("birth_status");

                    b.Property<string>("CaseCategory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_category");

                    b.Property<string>("CaseControlNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_control_no");

                    b.Property<string>("CaseStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_status");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentRiskLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("current_risk_level");

                    b.Property<DateTime?>("DateCaseStudyPrepared")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_case_study_prepared");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_closed");

                    b.Property<DateTime?>("DateColbObtained")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_colb_obtained");

                    b.Property<DateTime?>("DateColbRegistered")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_colb_registered");

                    b.Property<DateTime?>("DateEnrolled")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_enrolled");

                    b.Property<DateTime?>("DateOfAdmission")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_admission");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_birth");

                    b.Property<bool?>("FamilyIndigenous")
                        .HasColumnType("bit")
                        .HasColumnName("family_indigenous");

                    b.Property<bool?>("FamilyInformalSettler")
                        .HasColumnType("bit")
                        .HasColumnName("family_informal_settler");

                    b.Property<bool?>("FamilyIs4ps")
                        .HasColumnType("bit")
                        .HasColumnName("family_is_4ps");

                    b.Property<bool?>("FamilyParentPwd")
                        .HasColumnType("bit")
                        .HasColumnName("family_parent_pwd");

                    b.Property<bool?>("FamilySoloParent")
                        .HasColumnType("bit")
                        .HasColumnName("family_solo_parent");

                    b.Property<bool?>("HasSpecialNeeds")
                        .HasColumnType("bit")
                        .HasColumnName("has_special_needs");

                    b.Property<string>("InitialCaseAssessment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("initial_case_assessment");

                    b.Property<string>("InitialRiskLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("initial_risk_level");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("internal_code");

                    b.Property<bool?>("IsPwd")
                        .HasColumnType("bit")
                        .HasColumnName("is_pwd");

                    b.Property<string>("LengthOfStay")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("length_of_stay");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes_restricted");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("place_of_birth");

                    b.Property<string>("PresentAge")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("present_age");

                    b.Property<string>("PwdType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pwd_type");

                    b.Property<string>("ReferralSource")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("referral_source");

                    b.Property<string>("ReferringAgencyPerson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("referring_agency_person");

                    b.Property<string>("ReintegrationStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reintegration_status");

                    b.Property<string>("ReintegrationType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reintegration_type");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("religion");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sex");

                    b.Property<string>("SpecialNeedsDiagnosis")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("special_needs_diagnosis");

                    b.Property<bool?>("SubCatAtRisk")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_at_risk");

                    b.Property<bool?>("SubCatChildLabor")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_child_labor");

                    b.Property<bool?>("SubCatChildWithHiv")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_child_with_hiv");

                    b.Property<bool?>("SubCatCicl")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_cicl");

                    b.Property<bool?>("SubCatOrphaned")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_orphaned");

                    b.Property<bool?>("SubCatOsaec")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_osaec");

                    b.Property<bool?>("SubCatPhysicalAbuse")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_physical_abuse");

                    b.Property<bool?>("SubCatSexualAbuse")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_sexual_abuse");

                    b.Property<bool?>("SubCatStreetChild")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_street_child");

                    b.Property<bool?>("SubCatTrafficked")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_trafficked");

                    b.HasKey("ResidentId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("residents", (string)null);
                });

            modelBuilder.Entity("Intex2026.Api.Models.Safehouse", b =>
                {
                    b.Property<int>("SafehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SafehouseId"));

                    b.Property<int?>("CapacityGirls")
                        .HasColumnType("int")
                        .HasColumnName("capacity_girls");

                    b.Property<int?>("CapacityStaff")
                        .HasColumnType("int")
                        .HasColumnName("capacity_staff");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<int?>("CurrentOccupancy")
                        .HasColumnType("int")
                        .HasColumnName("current_occupancy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("OpenDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("open_date");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.Property<string>("SafehouseCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("safehouse_code");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("SafehouseId");

                    b.ToTable("safehouses", (string)null);
                });

            modelBuilder.Entity("Intex2026.Api.Models.Supporter", b =>
                {
                    b.Property<int>("SupporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("supporter_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupporterId"));

                    b.Property<string>("AcquisitionChannel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("acquisition_channel");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FirstDonationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("first_donation_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("organization_name");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("relationship_type");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("SupporterType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("supporter_type");

                    b.HasKey("SupporterId");

                    b.ToTable("supporters", (string)null);
                });

            modelBuilder.Entity("Intex2026.Api.Models.SocialMediaPost", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<string>("CampaignName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("campaign_name");

                    b.Property<int>("ClickThroughs")
                        .HasColumnType("int")
                        .HasColumnName("click_throughs");

                    b.Property<int>("Comments")
                        .HasColumnType("int")
                        .HasColumnName("comments");

                    b.Property<string>("ContentTopic")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_topic");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("DonationReferrals")
                        .HasColumnType("int")
                        .HasColumnName("donation_referrals");

                    b.Property<decimal?>("EngagementRate")
                        .HasColumnType("decimal(8,6)")
                        .HasColumnName("engagement_rate");

                    b.Property<decimal?>("EstimatedDonationValuePhp")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("estimated_donation_value_php");

                    b.Property<bool>("FeaturesResidentStory")
                        .HasColumnType("bit")
                        .HasColumnName("features_resident_story");

                    b.Property<int?>("FollowerCountAtPost")
                        .HasColumnType("int")
                        .HasColumnName("follower_count_at_post");

                    b.Property<bool>("HasCallToAction")
                        .HasColumnType("bit")
                        .HasColumnName("has_call_to_action");

                    b.Property<bool>("IsBoosted")
                        .HasColumnType("bit")
                        .HasColumnName("is_boosted");

                    b.Property<int>("Impressions")
                        .HasColumnType("int")
                        .HasColumnName("impressions");

                    b.Property<int>("Likes")
                        .HasColumnType("int")
                        .HasColumnName("likes");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("media_type");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("platform");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("post_type");

                    b.Property<int>("Reach")
                        .HasColumnType("int")
                        .HasColumnName("reach");

                    b.Property<string>("SentimentTone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sentiment_tone");

                    b.Property<int>("Shares")
                        .HasColumnType("int")
                        .HasColumnName("shares");

                    b.HasKey("PostId");

                    b.ToTable("social_media_posts", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Intex2026.Api.Models.Resident", b =>
                {
                    b.HasOne("Intex2026.Api.Models.Safehouse", "Safehouse")
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
